name: Continuous Deployment
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: macOS 10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Calculate Tag
        id: calculate_tag
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: Install Cargo Bump
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bump
      - name: Set Cargo Version
        uses: actions-rs/cargo@v1
        with:
          command: bump 
          args: ${{ steps.calculate_tag.outputs.new_tag }}
      - name: Push Tag
        id: push_tag
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.calculate_tag.outputs.new_tag }}
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.push_tag.outputs.new_tag }}
          release_name: Release ${{ steps.push_tag.outputs.new_tag }}
      - name: Create Archive
        run: |
          zip --junk-paths dl-darwin-amd64.zip target/release/dl
      - name: Upload Archive
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dl-darwin-amd64.zip
          asset_name: dl-${{ steps.push_tag.outputs.new_tag }}-darwin-amd64.zip
          asset_content_type: application/zip
