name: Continuous Deployment
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: macOS 10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Calculate Tag
        id: calculate-tag
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          tag_prefix: ''
      - name: Install Cargo Bump
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bump
      - name: Set Cargo Version
        uses: actions-rs/cargo@v1
        with:
          command: bump 
          args: ${{ steps.calculate-tag.outputs.new_tag }}
      - name: Push Tag
        id: push-tag
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.calculate-tag.outputs.new_tag }}
          tag_prefix: ''
      - name: Create GitHub Release
        uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.push-tag.outputs.new_tag }}
          release_name: Release ${{ steps.push-tag.outputs.new_tag }}
      - name: Create Archive
        run: |
          zip --junk-paths dl-darwin-amd64.zip target/release/dl
      - name: Upload Archive
        id: upload-archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dl-darwin-amd64.zip
          asset_name: dl-${{ steps.push-tag.outputs.new_tag }}-darwin-amd64.zip
          asset_content_type: application/zip
      - name: Trigger Homebrew Release
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: fraserdarwent/homebrew-dl
          event-type: new-release
          client-payload: '{"version": "${{ steps.push-tag.outputs.new_tag }}"}'
          
