name: Continuous Integration
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  compile:
    name: macOS 10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      # - name: Install Rustup
      #   run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      # - name: Install Rust
      #   run: rustup toolchain install 1.47.0
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
      - name: Compile
        run: cargo build --release
